language: node_js
node_js:
  - "6.11.0"
script:
    - npm run lint
    - npm run ci-test
after_script:
    - npm run send-coverage-data
env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - DB_USER=
    - DB_PASS=
    - DB_NAME=pokemon
    - DB_DIALECT=sqlite
    - DB_LOGGING=false
    # PAGARME_API_KEY added to Travis via console to ensure key privacy
before_install:
  - mysql -e 'CREATE DATABASE pokemon;'
