language: node_js
node_js:
  - "6.11.0"
script: npm test
env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - DB_USER=travis
    - DB_PASS=
    - DB_NAME=pokemon
    - DB_DIALECT=mysql
    - DB_LOGGING=false
    - PAGARME_API_KEY=ak_test_QFjQfNTUC9MhUzMrWTMvUBqPcW0vmE
before_install:
  - mysql -e 'CREATE DATABASE pokemon;'
